# Site settings
name: casey
email: email
url: url
description: "A blog and a portfolio"
author: "author"
title: "BlogCasey"
permalink: 
baseurl:

markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
   math_engine: mathjax
gems: [jekyll-paginate, jekyll-gist]
